version: '3.4'

services:
  yesinvestapi:
    image: yesinvestapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3004:3004
