version: '3.4'

services:
  yesinvestapi:
    image: yesinvestapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3004:3004
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
